version: "3.3"

services:
  rabbit:
    image: rabbitmq
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cluster-network

  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGODB_USER: "dev" 
      MONGODB_PASS: "dev"
    ports:
      - "27016:27016"

  fetcher:
    build: 
      context: ./services/fetcher
      dockerfile: Dockerfile
    hostname: fetcher
    networks:
      - cluster-network
  

networks:
  cluster-network:
    driver: bridge