version: "3.3"

services:

  rabbit:
    container_name: rabbit
    image: rabbitmq
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - cluster-network

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_UID
      POSTGRES_PASSWORD: $POSTGRES_PWD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - cluster-network

  fetcher:
    hostname: fetcher
    build:
      context: ./services/fetcher
      dockerfile: Dockerfile
    restart: always
    networks:
      - cluster-network

  storage:
    hostname: storage
    build:
      context: ./services/storage
      dockerfile: Dockerfile
    restart: always
    networks:
      - cluster-network

networks:
  cluster-network:
    driver: bridge
