// Code generated by sqlc. DO NOT EDIT.
// source: article.sql

package db

import (
	"context"
	"database/sql"
)

const createArticle = `-- name: CreateArticle :execresult
INSERT INTO articles (
    title,
    description,
    link,
    published,
    guid,
    is_loaded,
    checksum
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

func (q *Queries) CreateArticle(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createArticle)
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, description, link, published, guid, is_loaded, checksum FROM articles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArticle(ctx context.Context) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Published,
		&i.Guid,
		&i.IsLoaded,
		&i.Checksum,
	)
	return i, err
}
