// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Article struct {
	ID          int64          `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Link        sql.NullString `json:"link"`
	Published   sql.NullTime   `json:"published"`
	Guid        sql.NullString `json:"guid"`
	IsLoaded    sql.NullBool   `json:"is_loaded"`
	Checksum    sql.NullString `json:"checksum"`
}
